### Sign up as a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "elliegmail.com",
    "password": "el"
}

### Sign in as a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "harrycrav@gmail.com",
    "password": "123"
}

### Who am i 
GET http://localhost:3000/auth/whoami

### Sign out as a user
POST http://localhost:3000/auth/signout

### Get user by ID 
GET http://localhost:3000/auth/4

### Delete user by ID 
DELETE http://localhost:3000/auth/4


users = [
    {
        "email": "kendrick@gmail.com",
        "password": "goodKid"
    },
    {
        "email": "harrycrav@gmail.com",
        "password": "123"
    },
]