### Sign in as a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "harrycrav@gmail.com",
    "password": "123"
}

### Create new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "BMW",
    "model": "x5",
    "year": 2020,
    "mileage": 7900,
    "lng": 0,
    "lat": 0,
    "price": 45000
}

### Get estimate
GET  http://localhost:3000/reports?make=BMW&model=x5&lng=0&lat=0&mileage=5000&year=2020
content-type: application/json


### Get Report
GET  http://localhost:3000/reports/1
content-type: application/json

### Approve report
PATCH  http://localhost:3000/reports/1
content-type: application/json

{
    "approved": true
}





